<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Click_Add_Credit_Yes_Button</name>
   <tag></tag>
   <elementGuidId>2198771b-c008-4ec2-92e4-428731e7de16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-dashboard/div/main/div/ng-component/div[3]/div/div[2]/div/div[2]/div/div/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
