<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Click_ModeOfPayment_DropDown</name>
   <tag></tag>
   <elementGuidId>79a53d2d-9a11-4b95-9726-bfa3ed8ff1fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-dashboard/div/main/div/ng-component/div[3]/div[2]/div/div/div[3]/div[2]/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
